language: python
sudo: required
dist: xenial
install: "pip install -r requirements.txt"
matrix:
  include:
    - python: "3.6"
      env: TEST_CMD="make test"
    - python: "3.6"
      env: TEST_CMD="make lint"
    - python: "3.7"
      env: TEST_CMD="make test"
    - python: "3.7"
      env: TEST_CMD="make lint"
script: $TEST_CMD
